# Generated by Django 5.0.2 on 2024-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusergroup',
            options={'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
