# Generated by Django 5.0.3 on 2024-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
