# Generated by Django 5.0.2 on 2024-03-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_employee_gender_alter_employeephoto_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecontact', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedocument', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='employeephoto',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeephoto', to='hr_app.employee'),
        ),
    ]
