# Generated by Django 5.0.2 on 2024-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_employeecontact_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
