# Generated by Django 5.0.3 on 2024-03-21 18:49

import hr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_alter_employee_emp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeephoto',
            name='image',
            field=models.ImageField(default='media/staff/avatars/avatar.jpg', upload_to=hr_app.models.user_directory_path),
        ),
    ]
