# Generated by Django 5.0.3 on 2024-03-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalauthority',
            name='approval_authority_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='equipmentsubcategory',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='issuingrecord',
            name='issuing_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='itemsubcategory',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='orderingrecord',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
    ]
