# Generated by Django 5.0.3 on 2024-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_itemrequisition_approval_status_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
