# Generated by Django 5.0.3 on 2024-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_item_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(choices=[('', 'Select Dosage Form'), ('TB', 'Tablet'), ('CP', 'Capsule'), ('SY', 'Syrup'), ('IN', 'Injection'), ('CR', 'Cream'), ('OI', 'Ointment'), ('SU', 'Suppository'), ('LO', 'Lozenge'), ('PA', 'Patch'), ('AE', 'Aerosol')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemrequisitionitem',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
