# Generated by Django 5.0.3 on 2024-05-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_designation_title_alter_jobtype_title'),
        ('inventory_app', '0006_departmentinventory_delete_subdepartmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinventory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.department'),
        ),
    ]
