# Generated by Django 5.0.3 on 2024-05-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_designation_title_alter_jobtype_title'),
        ('inventory_app', '0008_alter_itemorder_ordered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='department',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.subdepartmentmaster'),
        ),
    ]
