# Generated by Django 5.0.3 on 2024-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_remove_itemorder_department_itemorder_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequisitionitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
