# Generated by Django 5.0.3 on 2024-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_itemrequisitionitem_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
