# Generated by Django 5.0.3 on 2024-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0011_storeorderitem_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
